---
functional:
  - Пользователь должнен иметь возможность регистрации
  - Пользователь должнен иметь возможность создания игры ("Create game") с выбором языка программирования
  - Победителем должен являться тот, кто верно решил задачу и затратил на это меньше времени 
  - У пользователя должна быть возможность настраивать параметры игры: сложность, выбор оппонента, лимит времени, тип задания 
  - У пользователя должна быть возможность создать поединок с другим пользователем/другом/ботом
  - У пользователя должна быть возможность сортировки таблицы лидеров по рейтингу, количеству игр и т.д
  - У пользователя должна быть возможность просмотра истории игр 
  - У пользователя должна быть возможность просмотра повтора игры 
  - У пользователя может быть возможность дописать код и/или ознакомиться с кодом соперника после завершения поединка
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность сыграть пробную игру, без регистрации
  - Пользователь должен иметь возможность регистрироваться на сайте, используя соц.сети или сервисы (Github, Discord)
  - Пользователь должен иметь возможность войти на сайте, используя соц.сети или сервисы (Github, Discord)
  - Пользователь должен иметь возможность просматривать свой профиль 
  - Пользователь может находиться только в одном баттле одновременно 
  - У пользователей должна быть возможность просматривать игры других пользователей онлайн
  - У зрителей не должно быть возможности писать код и вносить изменения в терминалах участников игры
  - Участник игры не может писать код в терминале соперника и изменять его
